//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvisClient
    {
        public int IdAvis { get; set; }
        public int Note { get; set; }
        public System.DateTime DateNote { get; set; }
        public int IdClient { get; set; }
        public int IdChambre { get; set; }
        public Nullable<bool> Approuve { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Chambre Chambre { get; set; }
        public virtual Client Client { get; set; }
    }
}
