//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestRooms
    {
        public int IdChambre { get; set; }
        public string Nom { get; set; }
        public string DescCourte { get; set; }
        public string DescLongue { get; set; }
        public int IdHostel { get; set; }
        public int IdType { get; set; }
        public int Capacite { get; set; }
        public Nullable<int> NbWc { get; set; }
        public Nullable<int> NbSdb { get; set; }
        public double Prix { get; set; }
        public Nullable<bool> EsTSupprimer { get; set; }
        public int IdAvis { get; set; }
        public int Note { get; set; }
        public System.DateTime DateNote { get; set; }
        public int IdClient { get; set; }
        public int Expr1 { get; set; }
        public Nullable<bool> Approuve { get; set; }
    }
}
