//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C5LastAvaibleRooms
    {
        public int IdChambre { get; set; }
        public string Nom { get; set; }
        public string DescCourte { get; set; }
        public string DescLongue { get; set; }
        public int IdHostel { get; set; }
        public int IdType { get; set; }
        public int Capacite { get; set; }
        public Nullable<int> NbWc { get; set; }
        public Nullable<int> NbSdb { get; set; }
        public double Prix { get; set; }
        public Nullable<bool> EsTSupprimer { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<System.DateTime> DateDeb { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<int> NbPers { get; set; }
        public Nullable<int> IdReservation { get; set; }
    }
}
