//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chambre
    {
        public Chambre()
        {
            this.AvisClient = new HashSet<AvisClient>();
            this.ChambrePhoto = new HashSet<ChambrePhoto>();
            this.Reservation = new HashSet<Reservation>();
            this.Service = new HashSet<Service>();
        }
    
        public int IdChambre { get; set; }
        public string Nom { get; set; }
        public string DescCourte { get; set; }
        public string DescLongue { get; set; }
        public int IdHostel { get; set; }
        public int IdType { get; set; }
        public int Capacite { get; set; }
        public Nullable<int> NbWc { get; set; }
        public Nullable<int> NbSdb { get; set; }
        public double Prix { get; set; }
        public Nullable<bool> EsTSupprimer { get; set; }
    
        public virtual ICollection<AvisClient> AvisClient { get; set; }
        public virtual Hostel Hostel { get; set; }
        public virtual TypeChambre TypeChambre { get; set; }
        public virtual ICollection<ChambrePhoto> ChambrePhoto { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
