//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChambrePhoto
    {
        public int IdChambre { get; set; }
        public int IdPhoto { get; set; }
        public Nullable<int> Ordre { get; set; }
    
        public virtual Chambre Chambre { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
