//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.AvisClient = new HashSet<AvisClient>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int IdClient { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Pseudo { get; set; }
        public string MotDePasse { get; set; }
    
        public virtual ICollection<AvisClient> AvisClient { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
