//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hostel
    {
        public Hostel()
        {
            this.Chambre = new HashSet<Chambre>();
            this.Service = new HashSet<Service>();
        }
    
        public int IdHostel { get; set; }
        public string Nom { get; set; }
        public int Etoiles { get; set; }
        public string Rue { get; set; }
        public int Numero { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }
        public string Pays { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Email { get; set; }
        public int NombreChambres { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<Chambre> Chambre { get; set; }
        public virtual ICollection<Service> Service { get; set; }
    }
}
