//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public Photo()
        {
            this.ChambrePhoto = new HashSet<ChambrePhoto>();
        }
    
        public int IdPhoto { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<ChambrePhoto> ChambrePhoto { get; set; }
    }
}
